name: Run Integration Tests

on: [push]

jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    services:
      database:
        image: "postgres:16.0-alpine3.18"
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: local_user
          POSTGRES_DB: local_db
          POSTGRES_PASSWORD: local_password
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm install
      - run: npx next dev &
      - run: npm run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: local_user
          POSTGRES_DB: local_db
          POSTGRES_PASSWORD: local_password
